name: website_snippets
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_riverpod:
    path: ../packages/flutter_riverpod
  freezed_annotation: ^2.2.0
  hooks_riverpod:
    path: ../packages/hooks_riverpod
  json_annotation: ^4.8.0
  mockito: ^5.0.0
  riverpod:
    path: ../packages/riverpod
  riverpod_annotation:
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner:
  build_verify: ^3.0.0
  cosmic_frontmatter:
    path: third-party/cosmic_frontmatter
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  glob: ^2.1.0
  http: ^0.13.5
  json_serializable: ^6.6.1
  path: ^1.8.1
  riverpod_generator:

flutter:
  uses-material-design: true
